services:
  client:
    build:
      context: ./client
      target: ${ENVIRONMENT}
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    depends_on:
      - server

  server:
    build:
      context: ./server
      target: ${ENVIRONMENT}
    ports:
      - "3002:3002"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env