services:
  client:
    build:
      context: ./client
      target: ${ENVIRONMENT}
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    depends_on:
      server:
        condition: service_healthy

  server:
    build:
      context: ./server
      target: ${ENVIRONMENT}
    ports:
      - "3002:3002"
    volumes:
      - ./server:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:3002/health"]
      interval: 12h
      timeout: 5s
      retries: 3
      start_period: 5s
    env_file:
      - .env